# Site settings
title: My Site
url: https://www.example.com

# Plugin to enable redirect handling
plugins:
  - jekyll-redirect-from 

# Set global redirect defaults
defaults:
  - scope:
      path: "/*" # Matches all paths
    values:
      status: 200 # Set status to 200

# Actual redirect mappings 
redirects:
  - "/*": "/404.html" # Redirect all undefined URLs to 404.html

# Permalink structure
permalink: /post/:id

# Other config...
